-- ============================================================
-- ORDER SCHEMAS - pro_restaurant database
-- ============================================================
-- Regular Orders  : orders, order_details
-- Catering Orders : catering_orders, catering_order_details
-- Common          : order_history (used by both)
-- Linking Key     : orders.code / catering_orders.code
--                   ↔ order_details.order_code / catering_order_details.order_code
--                   ↔ order_history.order_id
-- ============================================================


-- ============================================================
-- 1. REGULAR ORDERS
-- ============================================================

CREATE TABLE `orders` (
  `id` int NOT NULL AUTO_INCREMENT,
  `delivery_to_pickup` tinyint(1) DEFAULT '0',
  `delivery_to_pickup_time` bigint DEFAULT NULL,
  `delivery_to_pickup_time_15` bigint DEFAULT NULL,
  `auto_cancel` tinyint(1) DEFAULT '0',
  `delivery_api_failed` tinyint(1) NOT NULL DEFAULT '0',
  `flag` tinyint(1) NOT NULL DEFAULT '1',
  `rs` tinyint(1) DEFAULT '0',
  `pos` tinyint(1) DEFAULT '0',
  `dc` bigint DEFAULT '0',
  `pu_status` int NOT NULL DEFAULT '0',
  `spu_status` int DEFAULT '0',
  `delay_status` tinyint(1) DEFAULT '0',
  `show_status` int NOT NULL DEFAULT '0',
  `coupon_amount` float(65,2) DEFAULT '0.00',
  `coupon_code` varchar(255) DEFAULT NULL,
  `coupon_id` varchar(100) DEFAULT NULL,
  `caterign_charge_percentage_value` bigint DEFAULT NULL,
  `catering_change_title` varchar(255) DEFAULT NULL,
  `catering_change` float(65,2) DEFAULT '0.00',
  `delivery_track_id` text,
  `quote_estimate_id` text,
  `cancel_fee` text,
  `increment_val` bigint DEFAULT NULL,
  `increment_status` tinyint(1) DEFAULT '0',
  `cart_data` text,
  `strip_pass_amt` decimal(10,2) DEFAULT NULL,
  `order_amount` text,
  `email_sending_status` tinyint(1) DEFAULT '0',
  `strip_payment_key` text,
  `delivery_api_status` varchar(255) DEFAULT NULL,
  `delivery_notes` text,
  `complete_email` tinyint(1) DEFAULT '0',
  `code` varchar(255) DEFAULT NULL,
  `oid` bigint DEFAULT '0',
  `customer_id` int DEFAULT NULL,
  `customer_address_id` int DEFAULT NULL,
  `driver_id` int DEFAULT NULL,
  `order_placed_at` int DEFAULT NULL,
  `order_approved_at` int DEFAULT NULL,
  `order_preparing_at` int DEFAULT NULL,
  `order_prepared_at` int DEFAULT NULL,
  `order_ready_at` int DEFAULT NULL,
  `order_initiated_at` int DEFAULT NULL,
  `order_trip_created_at` int DEFAULT NULL,
  `order_in_progress_at` int DEFAULT NULL,
  `order_returned_at` int DEFAULT NULL,
  `order_delayed_at` int DEFAULT NULL,
  `order_pickup_at` int DEFAULT NULL,
  `order_picked_up_at` int DEFAULT NULL,
  `order_auto_cancel_at` int DEFAULT NULL,
  `order_delivered_at` int DEFAULT NULL,
  `order_pickuped_at` bigint DEFAULT NULL,
  `order_canceled_at` int DEFAULT NULL,
  `order_delivery_canceled_at` bigint DEFAULT NULL,
  `order_assigned_at` bigint DEFAULT NULL,
  `order_scheduled_at` bigint DEFAULT NULL,
  `order_status` varchar(255) DEFAULT NULL,
  `note` longtext,
  `total_menu_price` float(65,2) DEFAULT '0.00',
  `total_delivery_charge` float(65,2) DEFAULT '0.00',
  `total_vat_amount` float(65,2) DEFAULT '0.00',
  `service_fee` text,
  `tips_amount` float(65,2) DEFAULT '0.00',
  `grand_total` float(65,2) DEFAULT '0.00',
  `payment_method` varchar(255) DEFAULT NULL,
  `payment_details` longtext,
  `payment_timestamp` longtext,
  `payment_status` longtext,
  `type` varchar(255) DEFAULT 'pickup',
  `order_schedule_mode` text,
  `strip_status` bigint DEFAULT '0',
  `store_address` longtext,
  `store_location` text,
  `day` text,
  `schedule` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `lastname` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `mobile` varchar(255) DEFAULT NULL,
  `phone_isd_code` varchar(5) DEFAULT '+1',
  `apartment` varchar(255) DEFAULT NULL,
  `delivery_add` longtext,
  `delivery_address_type` varchar(50) DEFAULT NULL,
  `deliver_cod` longtext,
  `order_type` varchar(255) DEFAULT NULL,
  `order_mode` int NOT NULL DEFAULT '0',
  `order_schedule` varchar(255) DEFAULT NULL,
  `order_schedule_time` varchar(255) DEFAULT NULL,
  `deliveryStatus` tinyint(1) DEFAULT '0',
  `admin_refund` varchar(255) DEFAULT '0',
  `created_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `ip_data` longtext,
  `receipt_url` longtext,
  `stripe_charge` longtext,
  `stripe_capture` longtext,
  `refund_details` json DEFAULT NULL,
  `tracking_info` json DEFAULT NULL,
  `admin_discount` double(10,2) DEFAULT '0.00',
  `admin_add` double(10,2) DEFAULT '0.00',
  `admin_reason` text,
  `stripe_create_array` text,
  `stripe_create_array_data` text,
  `alert_5` tinyint(1) DEFAULT '0',
  `alert_10` tinyint(1) DEFAULT '0',
  `alert_15` tinyint(1) DEFAULT '0',
  `alert_20` tinyint(1) DEFAULT '0',
  `alert_30` tinyint(1) DEFAULT '0',
  `alert_25` tinyint(1) DEFAULT '0',
  `alert_60` tinyint(1) DEFAULT '0',
  `alert_120` tinyint(1) DEFAULT '0',
  `alert_180` tinyint(1) DEFAULT '0',
  `stripe_payment_intent_id` text,
  `partyware` varchar(119) DEFAULT NULL,
  `order_source` varchar(50) NOT NULL DEFAULT 'web',
  `tracking_token` varchar(32) DEFAULT NULL,
  `show_order_in_app` tinyint NOT NULL DEFAULT '1',
  `pos_note` text,
  `pos_order_api` text,
  `pos_order_request` text,
  `pos_order_response` text,
  `pos_orderId` varchar(100) DEFAULT NULL,
  `pos_cancel_api` text,
  `pos_cancel_request` text,
  `pos_cancel_response` text,
  `redemption_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT 'Redemption amount used in this order',
  `user_selection` varchar(50) DEFAULT NULL,
  `kiosk_order_id` varchar(50) DEFAULT NULL,
  `order_token` varchar(255) NOT NULL DEFAULT '',
  `token_expiry` varchar(255) NOT NULL DEFAULT '',
  `token_status` enum('0','1','2','3','4','5') NOT NULL DEFAULT '0' COMMENT '0-Unused,1-Used,2-Expired,3-Accepted from merchant app,4-Accepted from super admin,5-Accepted from merchant portal',
  PRIMARY KEY (`id`),
  UNIQUE KEY `tracking_token` (`tracking_token`),
  KEY `customer_id` (`customer_id`),
  KEY `driver_id` (`driver_id`),
  KEY `code` (`code`),
  KEY `order_status` (`order_status`),
  KEY `oid` (`oid`),
  KEY `idx_orders_coupon` (`customer_id`,`coupon_code`,`coupon_id`),
  KEY `idx_orders_coupon_check` (`coupon_id`,`customer_id`,`oid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;


-- ============================================================
-- 2. REGULAR ORDER DETAILS
-- ============================================================

CREATE TABLE `order_details` (
  `id` int NOT NULL AUTO_INCREMENT,
  `edit_status` tinyint(1) NOT NULL DEFAULT '0',
  `order_code` varchar(255) DEFAULT NULL,       -- FK → orders.code
  `menu_id` int DEFAULT NULL,
  `menu_name` text,
  `unit` text,
  `servings` varchar(255) DEFAULT NULL,
  `quantity` int DEFAULT NULL,
  `order_quantity` bigint DEFAULT NULL,
  `total` varchar(255) DEFAULT NULL,
  `restaurant_id` int DEFAULT NULL,
  `add_on` longtext,
  `orig_details` text,
  `instructions` longtext,
  `created_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `original_price` decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `order_code` (`order_code`),
  KEY `restaurant_id` (`restaurant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;


-- ============================================================
-- 3. CATERING ORDERS
-- ============================================================

CREATE TABLE `catering_orders` (
  `id` int NOT NULL AUTO_INCREMENT,
  `delivery_to_pickup` tinyint(1) DEFAULT '0',
  `delivery_to_pickup_time` bigint DEFAULT NULL,
  `delivery_to_pickup_time_15` bigint DEFAULT NULL,
  `auto_cancel` tinyint(1) DEFAULT '0',
  `delivery_api_failed` tinyint(1) NOT NULL DEFAULT '0',
  `flag` tinyint(1) NOT NULL DEFAULT '1',
  `rs` tinyint(1) DEFAULT '0',
  `pos` tinyint(1) DEFAULT '0',
  `dc` bigint DEFAULT '0',
  `pu_status` int DEFAULT '0',
  `spu_status` int DEFAULT '0',
  `delay_status` tinyint(1) DEFAULT '0',
  `show_status` tinyint(1) DEFAULT '0',
  `delivery_track_id` text,
  `quote_estimate_id` text,
  `cancel_fee` text,
  `increment_val` bigint DEFAULT NULL,
  `increment_status` tinyint(1) DEFAULT '0',
  `cart_data` text,
  `strip_pass_amt` text,
  `order_amount` text,
  `pos_different_amount` text,
  `admin_discount` double(10,2) DEFAULT '0.00',
  `admin_add` double(10,2) DEFAULT '0.00',
  `admin_reason` text,
  `pack` tinyint(1) DEFAULT '0',
  `strip_payment_key` text,
  `delivery_api_status` varchar(255) DEFAULT NULL,
  `delivery_notes` text,
  `complete_email` tinyint(1) DEFAULT '0',
  `code` varchar(255) DEFAULT NULL,
  `oid` bigint DEFAULT '0',
  `customer_id` int DEFAULT NULL,
  `customer_address_id` int DEFAULT NULL,
  `driver_id` int DEFAULT NULL,
  `order_placed_at` int DEFAULT NULL,
  `order_approved_at` int DEFAULT NULL,
  `order_preparing_at` int DEFAULT NULL,
  `order_prepared_at` int DEFAULT NULL,
  `order_ready_at` int DEFAULT NULL,
  `order_initiated_at` int DEFAULT NULL,
  `order_trip_created_at` int DEFAULT NULL,
  `order_in_progress_at` int DEFAULT NULL,
  `order_returned_at` int DEFAULT NULL,
  `order_delayed_at` int DEFAULT NULL,
  `order_pickup_at` int DEFAULT NULL,
  `order_picked_up_at` int DEFAULT NULL,
  `order_auto_cancel_at` int DEFAULT NULL,
  `order_delivered_at` int DEFAULT NULL,
  `order_pickuped_at` bigint DEFAULT NULL,
  `order_canceled_at` int DEFAULT NULL,
  `order_delivery_canceled_at` bigint DEFAULT NULL,
  `order_assigned_at` bigint DEFAULT NULL,
  `order_scheduled_at` bigint DEFAULT NULL,
  `order_status` varchar(255) DEFAULT NULL,
  `note` longtext,
  `total_menu_price` float(65,2) DEFAULT '0.00',
  `total_delivery_charge` float(65,2) DEFAULT '0.00',
  `total_vat_amount` float(65,2) DEFAULT '0.00',
  `service_fee` text,
  `tips_amount` float(65,2) DEFAULT '0.00',
  `coupon_amount` float(65,2) NOT NULL DEFAULT '0.00',
  `coupon_code` varchar(255) DEFAULT NULL,
  `coupon_id` varchar(100) DEFAULT '',
  `caterign_charge_percentage_value` bigint DEFAULT NULL,
  `catering_change_title` varchar(255) DEFAULT NULL,
  `catering_change` float(65,2) DEFAULT '0.00',
  `grand_total` float(65,2) DEFAULT '0.00',
  `payment_method` varchar(255) DEFAULT NULL,
  `payment_details` longtext,
  `payment_timestamp` longtext,
  `payment_status` longtext,
  `type` varchar(255) DEFAULT 'pickup',
  `order_schedule_mode` text,
  `strip_status` bigint DEFAULT '0',
  `store_address` longtext,
  `store_location` text,
  `day` text,
  `schedule` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `lastname` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `mobile` varchar(255) DEFAULT NULL,
  `phone_isd_code` varchar(5) DEFAULT '+1',
  `apartment` varchar(255) DEFAULT NULL,
  `delivery_add` longtext,
  `delivery_address_type` varchar(50) DEFAULT NULL,
  `deliver_cod` longtext,
  `order_type` varchar(255) DEFAULT NULL,
  `order_mode` int NOT NULL DEFAULT '0',
  `partyware` varchar(100) NOT NULL,
  `order_schedule` varchar(255) DEFAULT NULL,
  `order_schedule_time` varchar(255) DEFAULT NULL,
  `deliveryStatus` tinyint(1) DEFAULT '0',
  `admin_refund` varchar(255) DEFAULT '0',
  `pos_note` text,
  `pos_order_api` text,
  `pos_order_request` text,
  `pos_order_response` text,
  `pos_orderId` text,
  `pos_cancel_api` text,
  `pos_cancel_request` text,
  `pos_cancel_response` text,
  `created_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `ip_data` longtext,
  `stripe_create_array` text,
  `stripe_create_array_data` text,
  `alert_5` tinyint(1) DEFAULT '0',
  `alert_10` tinyint(1) DEFAULT '0',
  `alert_15` tinyint(1) DEFAULT '0',
  `alert_20` tinyint(1) DEFAULT '0',
  `alert_25` tinyint(1) DEFAULT '0',
  `alert_30` tinyint(1) DEFAULT '0',
  `alert_60` tinyint(1) DEFAULT '0',
  `alert_120` tinyint(1) DEFAULT '0',
  `alert_180` tinyint(1) DEFAULT '0',
  `receipt_url` longtext,
  `stripe_charge` longtext,
  `stripe_capture` longtext,
  `refund_details` json DEFAULT NULL,
  `tracking_info` json DEFAULT NULL,
  `stripe_payment_intent_id` text,
  `order_source` varchar(50) NOT NULL DEFAULT 'web',
  `tracking_token` varchar(34) DEFAULT NULL,
  `show_order_in_app` tinyint NOT NULL DEFAULT '1',
  `redemption_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT 'Redemption amount used in this order',
  `user_selection` varchar(50) DEFAULT NULL,
  `kiosk_order_id` varchar(50) DEFAULT NULL,
  `order_token` varchar(255) NOT NULL DEFAULT '',
  `token_expiry` varchar(255) NOT NULL DEFAULT '',
  `token_status` enum('0','1','2','3','4','5') NOT NULL DEFAULT '0' COMMENT '0-Unused,1-Used,2-Expired,3-Accepted from merchant app,4-Accepted from super admin,5-Accepted from merchant portal',
  PRIMARY KEY (`id`),
  UNIQUE KEY `tracking_token` (`tracking_token`),
  KEY `idx_catering_orders_coupon` (`customer_id`,`coupon_code`,`coupon_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;


-- ============================================================
-- 4. CATERING ORDER DETAILS
-- ============================================================

CREATE TABLE `catering_order_details` (
  `id` int NOT NULL AUTO_INCREMENT,
  `edit_status` tinyint(1) NOT NULL DEFAULT '0',
  `order_code` varchar(255) DEFAULT NULL,       -- FK → catering_orders.code
  `menu_id` text,
  `menu_name` longtext,
  `unit` varchar(255) DEFAULT NULL,
  `servings` varchar(255) DEFAULT NULL,
  `quantity` int DEFAULT NULL,
  `order_quantity` bigint DEFAULT NULL,
  `total` varchar(255) DEFAULT NULL,
  `restaurant_id` int DEFAULT NULL,
  `add_on` longtext,
  `instructions` longtext,
  `created_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;


-- ============================================================
-- 5. ORDER HISTORY (Common — used by both Regular & Catering)
-- ============================================================

CREATE TABLE `order_history` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `order_id` varchar(50) NOT NULL,             -- FK → orders.code OR catering_orders.code
  `process_by` varchar(50) NOT NULL,
  `particulars` text NOT NULL,
  `time_format` bigint NOT NULL,
  `created_data` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

