import pytest
import os
import tempfile
import json
from boons_text_to_sql_agent.domain import Role
from scripts.ingest_schema import (
    update_static_schema, 
    append_test_cases, 
    append_rag_docs,
    SchemaDoc, TableDef, ColumnDef, RelationshipDef,
    TestCasesDoc, TestCaseDef,
    KnowledgeBaseDoc, RagDocumentDef
)

# Dummy payloads generated by LLM parsing
DUMMY_SCHEMA = SchemaDoc(
    tables=[
        TableDef(
            name="dummy_inventory",
            description="Table for holding stock data.",
            columns=[
                ColumnDef(name="id", description="Primary key"),
                ColumnDef(name="item_name", description="Name of the item")
            ]
        )
    ],
    relationships=[
        RelationshipDef(**{"from": "dummy_inventory.restaurant_id", "to": "restaurant.id"})
    ]
)

DUMMY_TEST_CASES = TestCasesDoc(
    test_cases=[
        TestCaseDef(
            question="What is the stock level of item X?",
            role="MERCHANT",
            merchant_ids=[1],
            expected_to_be_sql=True
        ),
        TestCaseDef(
            question="Hi there AI",
            role="INTERNAL",
            merchant_ids=[],
            expected_to_be_sql=False
        )
    ]
)

DUMMY_RAG_DOCS = KnowledgeBaseDoc(
    documents=[
        RagDocumentDef(
            page_content="When user asks 'stock', filter dummy_inventory.",
            category="synonym",
            table="dummy_inventory"
        )
    ]
)

def test_append_test_cases(monkeypatch):
    """Test that test cases are correctly appended with proper Python syntax."""
    
    # Mock file with a simplified structure simulating scripts/test_suite.py
    mock_content = '''TEST_CASES = [
    TestCase("Existing test", Role.INTERNAL, [0]),
]

async def main():
    pass
'''
    with tempfile.NamedTemporaryFile("w+", delete=False, suffix=".py") as tf:
        tf.write(mock_content)
        mock_path = tf.name

    # Patch os.path.join so append_test_cases grabs our mock file instead of the real one
    original_join = os.path.join
    def patched_join(*args, **kwargs):
        if args == ("scripts", "test_suite.py"):
            return mock_path
        return original_join(*args, **kwargs)
        
    monkeypatch.setattr(os.path, "join", patched_join)

    try:
        append_test_cases(DUMMY_TEST_CASES)
        
        with open(mock_path, "r") as f:
            new_content = f.read()
            
        # Verify the new tests are inside the list before the closing bracket
        assert 'TestCase("What is the stock level of item X?", Role.MERCHANT, [1])' in new_content
        assert 'TestCase("Hi there AI", Role.INTERNAL, [], expected_to_be_sql=False)' in new_content
        
        # Verify it didn't break the brackets
        assert new_content.count("[") > 0
        assert new_content.count("]") > 0
        
        # Verify the list ends correctly followed by main()
        assert "]\n\nasync def main():" in new_content
        
         # Verify a trailing comma was inserted to prevent syntax errors on the existing list
        assert 'TestCase("Existing test", Role.INTERNAL, [0]),\n    TestCase' in new_content
    finally:
        os.remove(mock_path)


def test_append_rag_docs(monkeypatch):
    """Test that RAG docs are appended properly to build_knowledge_base.py"""
    
    mock_content = '''KNOWLEDGE_DOCS = [
    Document(
        page_content="Existing doc",
        metadata={"category": "general"}
    ),
]

def build_index():
    pass
'''
    with tempfile.NamedTemporaryFile("w+", delete=False, suffix=".py") as tf:
        tf.write(mock_content)
        mock_path = tf.name

    original_join = os.path.join
    def patched_join(*args, **kwargs):
        if args == ("scripts", "build_knowledge_base.py"):
            return mock_path
        return original_join(*args, **kwargs)
        
    monkeypatch.setattr(os.path, "join", patched_join)

    try:
        append_rag_docs(DUMMY_RAG_DOCS)
        
        with open(mock_path, "r") as f:
            new_content = f.read()
            
        assert 'page_content="When user asks \'stock\', filter dummy_inventory."' in new_content
        assert '"category": "synonym"' in new_content
        assert '"table": "dummy_inventory"' in new_content
        
        # Ensure it didn't create a double-comma syntax error from the previous line
        assert "),," not in new_content
        
        # Verify the list ends appropriately
        assert "]\n\ndef build_index():" in new_content
    finally:
        os.remove(mock_path)

def test_update_static_schema(monkeypatch):
    """Test that dictionary injection into static_schema_provider.py works safely."""
    
    # We must simulate the very specific indentation and brackets
    mock_content = '''class StaticSchemaProvider(SchemaProviderPort):
    def get_schema_manifest(self, scope: Scope) -> Mapping[str, Any]:
        base_schema: Dict[str, Any] = {
            "tables": {
                                "existing_table": {
                    "description": "Blah",
                    "columns": {"id": "key"}
                }
            },
            "relationships": [
                                {
                                            "from": "a.id",
                                            "to": "b.id"
                                }
            ]
        }

        if scope.role == Role.MERCHANT:
            base_schema["role"] = "merchant"
        else:
            base_schema["role"] = "internal"

        return base_schema
'''
    with tempfile.NamedTemporaryFile("w+", delete=False, suffix=".py") as tf:
        tf.write(mock_content)
        mock_path = tf.name

    original_join = os.path.join
    def patched_join(*args, **kwargs):
        if "static_schema_provider.py" in args[-1]:
            return mock_path
        return original_join(*args, **kwargs)
        
    monkeypatch.setattr(os.path, "join", patched_join)

    try:
        update_static_schema(DUMMY_SCHEMA)
        
        with open(mock_path, "r") as f:
            new_content = f.read()
            
        # Check newly appended table
        assert '"dummy_inventory": {' in new_content
        assert '"description": "Table for holding stock data."' in new_content
        assert '"id": "Primary key"' in new_content
        
        # Check newly appended relationship
        assert '"from": "dummy_inventory.restaurant_id"' in new_content
        assert '"to": "restaurant.id"' in new_content
        
        # Verify no trailing commas broke the schema parsing
        assert "}" in new_content
        # Ensure it didn't duplicate the insertion segment accidentally
        assert new_content.count('"dummy_inventory"') == 1
    finally:
        os.remove(mock_path)
